birds = {"nodes": [
    {"commonName": "Chicken",
     "sciName": "Gallus gallus",
     "about": "Native to Southern Asia, particularly the jungles of India. The plumage is gold, red, brown, dark maroon, and orange, with metallic green and gray. There are also some white and olive feathers.",
     "group": 1},

    {"commonName": "Chachalacas",
     "sciName": "Ortalis ruficauda",
     "about": "Chachalacas are galliform birds from the genus Ortalis. These birds are found in wooded habitats in the far southern United States, Mexico, and Central and South America.",
     "group": 1},

    {"commonName": "Golden Pheasant",
     "sciName": "Chrysolophus pictus",
     "about": "The golden pheasant, also known as the Chinese pheasant, and rainbow pheasant, is a gamebird of the order Galliformes and the family Phasianidae. The genus name is from Ancient Greek khrusolophos, with golden crest, and pictus is Latin for painted from pingere, to paint.",
     "group": 1},

    {"commonName": "Mallard",
     "sciName": "Anas platyrhynchos",
     "about": "The Mallard is the ancestor of nearly all domestic duck breeds. Mallard pairs are generally monogamous, but paired males pursue females other than their mates.",
     "group": 1},

    {"commonName": "Galliformes",
     "sciName": "Galliformes",
     "about": "Galliformes is an order of heavy-bodied ground-feeding birds that includes turkeys, chickens, quail, and other landfowl. Gallinaceous birds, as they are called, are important in their ecosystems as seed dispersers and predators, and are often reared by humans for their meat and eggs, or hunted as game birds.",
     "group": 10},

    {"commonName": "Roufus Hummingbird",
     "sciName": "Selasphorus rufus",
     "about": "The rufous hummingbird is a small hummingbird, about 8 cm long with a long, straight and slender bill. These birds are known for their extraordinary flight skills, flying 2,000 miles during their migratory transits. It is one of nine species in the genus Selasphorus.",
     "group": 2},

    {"commonName": "Common Nighthawk",
     "sciName": "Chordeiles minor",
     "about": "The common nighthawk is a medium-sized crepuscular or nocturnal bird of the Americas within the nightjar family, whose presence and identity are best revealed by its vocalization. Typically dark, displaying cryptic coloration and intricate patterns, this bird is difficult to spot with the naked eye during the day",
     "group": 2},

    {"commonName": "Chimney Swift",
     "sciName": "Chaetura pelagica",
     "about": "A bird best identified by silhouette, the smudge-gray Chimney Swift nimbly maneuvers over rooftops, fields, and rivers to catch insects.",
     "group": 2},

    {"commonName": "Great Blue Turaco",
     "sciName": "Corythaeola cristata",
     "about": "The great blue turaco is a bird species of the family Musophagidae. At 70–76 cm in length, it is the largest species of turaco. It has predominantly grey-blue plumage with an upright blue-black crest around 10 cm high. The male and female have similar plumage.",
     "group": 2},

    {"commonName": "Strisores",
     "sciName": "Strisores",
     "about": "Strisores is a clade of birds that includes the living families and orders Caprimulgidae, Nyctibiidae, Steatornithidae, Podargidae, Apodiformes, as well as the Aegotheliformes whose distinctness was only recently realized. The Apodiformes and the Aegotheliformes form the Daedalornithes.",
     "group": 20},

    {"commonName": "Rock Dove",
     "sciName": "Columba livia",
     "about": "The rock dove, rock pigeon, or common pigeon is a member of the bird family Columbidae. In common usage, it is often simply referred to as the pigeon. The domestic pigeon descended from this species. Escaped domestic pigeons have increased the populations of feral pigeons around the world.",
     "group": 3},

    {"commonName": "Bengal Florican",
     "sciName": "Houbaropsis bengalensis",
     "about": "The Bengal florican, also called the Bengal bustard, is a bustard species native to the Indian subcontinent, Cambodia, and Vietnam. It is listed as Critically Endangered on the IUCN Red List because fewer than 1,000 individuals were estimated to be alive as of 2017.",
     "group": 3},

    {"commonName": "Common Cuckoo",
     "sciName": "Cuculus canorus",
     "about": "The common cuckoo is a member of the cuckoo order of birds, Cuculiformes, which includes the roadrunners, the anis and the coucals. This species is a widespread summer migrant to Europe and Asia, and winters in Africa.",
     "group": 3},

    {"commonName": "Greater Roadrunner",
     "sciName": "Geococcyx californianus",
     "about": "The roadrunners, also known as chaparral birds or chaparral cocks, are two species of fast-running ground cuckoos with long tails and crests. They are found in the southwestern and south-central United States and Mexico, usually in the desert. Although capable of flight, roadrunners generally run away from predators.",
     "group": 3},

    {"commonName": "Black-bellied Sandgrouse",
     "sciName": "Pterocles orientalis",
     "about": "Subtly beautiful shuffling pigeonlike bird with a small head, striking black belly, and pale breast that contrasts with white underwings and black wingtips.",
     "group": 3},

    {"commonName": "Columbaves",
     "sciName": "Columbaves",
     "about": "Columbaves is a clade that contains Columbimorphae (pigeons, mesites, and sandgrouse) and Otidimorphae (bustards, cuckoos, and turacos).",
     "group": 30},

    {"commonName": "Greater Flamingo",
     "sciName": "Phoenicopterus ruber",
     "about": "The greater flamingo is the most widespread and largest species of the flamingo family. It is found in Africa, the Indian subcontinent, the Middle East, and in southern Europe.",
     "group": 4},

    {"commonName": "Pied-billed Grebe",
     "sciName": "Podilymbus podiceps",
     "about": "The pied-billed grebe is a species of the grebe family of water birds. Because the Atitlán grebe has become extinct, the Pied-Billed Grebe is now the sole extant member of the genus Podilymbus. The pied-billed grebe is primarily found in ponds throughout the Americas.",
     "group": 4},

    {"commonName": "Piping Plover",
     "sciName": "Charadrius melodus",
     "about": "The piping plover is a small sand-colored, sparrow-sized shorebird that nests and feeds along coastal sand and gravel beaches in North America. The adult has yellow-orange-red legs, a black band across the forehead from eye to eye, and a black stripe running along the breast line.",
     "group": 4},

    {"commonName": "Snowy Plover",
     "sciName": "Charadrius nivosus",
     "about": "The dapper Snowy Plover scurries across sandy habitats as inconspicuously as a puff of sea foam blown by the wind. Unfortunately, the snowy plover's population has been dramatically decreasing.",
     "group": 4},

    {"commonName": "American Oystercatcher",
     "sciName": "Haematopus palliatus",
     "about": "The American oystercatcher, occasionally called the American pied oystercatcher, is a member of family Haematopodidae. Originally called the sea pie, it was renamed in 1731 when naturalist Mark Catesby observed the bird eating oysters. The current population of American oystercatchers is estimated to be 43,000",
     "group": 4},

    {"commonName": "Least Sandpiper",
     "sciName": "Calidris minutilla",
     "about": "The least sandpiper is the smallest shorebird. The genus name is from Ancient Greek kalidris or skalidris, a term used by Aristotle for some grey-colored waterside birds. The specific minutilla is Medieval Latin for very small.",
     "group": 4},

    {"commonName": "Sandwich Tern",
     "sciName": "Thalasseus sandvicensis",
     "about": "The Sandwich tern is a tern in the family Laridae. It is very closely related to the lesser crested tern, Chinese crested tern, Cabot's tern, and elegant tern and has been known to interbreed with the lesser crested.",
     "group": 4},

    {"commonName": "Laughing Gull",
     "sciName": "Leucophaeus atricilla",
     "about": "The laughing gull is a medium-sized gull of North and South America. Named for its laugh-like call, it is an opportunistic omnivore and scavenger. It breeds in large colonies mostly along the Atlantic coast of North America, the Caribbean, and northern South America.",
     "group": 4},

    {"commonName": "Herring Gull",
     "sciName": "Larus argentatus",
     "about": "The European herring gull is a large gull, up to 66 cm long. One of the best-known of all gulls along the shores of Western Europe, it was once abundant. It breeds across Northern Europe, Western Europe, Central Europe, Eastern Europe, Scandinavia, and the Baltic states.",
     "group": 4},

    {"commonName": "Arctic Tern",
     "sciName": "Sterna paradisaea",
     "about": "The Arctic tern is a tern in the family Laridae.\n"
              "This bird has a circumpolar breeding distribution \n"
              "covering the Arctic and sub-Arctic regions of Europe,\n"
              "Asia, and North America.",
     "group": 4},

    {"commonName": "Black Skimmer",
     "sciName": "Rynchops niger",
     "about": "The black skimmer is a tern-like seabird, one of three similar bird species in the skimmer genus Rynchops in the gull family Laridae. It breeds in North and South America.",
     "group": 4},

    {"commonName": "Atlantic Puffin",
     "sciName": "Fratercula arctica",
     "about": "The Atlantic puffin, also known as the common puffin, is a species of seabird in the auk family. It is the only puffin native to the Atlantic Ocean; two related species, the tufted puffin and the horned puffin is found in the northeastern Pacific.",
     "group": 4},

    {"commonName": "Aequorlitornithes",
     "sciName": "Aequorlitornithes",
     "about": "Aequorlitornithes is a clade of waterbirds recovered in a comprehensive genomic systematic study using nearly 200 species in 2015. It contains the clades Charadriiformes, Mirandornithes, and Phaethoquornithes. Previous studies have found different placement for the clades in the tree.",
     "group": 40},

    {"commonName": "Belted Kingfisher",
     "sciName": "Megaceryle alcyon",
     "about": "The Belted Kingfisher is one of the few bird species in which the female is more brightly colored than the male. It is a large, conspicuous water kingfisher, native to North America. Informally speaking, they are very cool :)",
     "group": 5},

    {"commonName": "Speckled Mousebird",
     "sciName": "Colius striatus",
     "about": "The speckled mousebird is the largest species of mousebird, as well as one of the most common. It is found throughout most of Central, Eastern, and Southern Africa.",
     "group": 5},

    {"commonName": "Toco Toucan",
     "sciName": "Ramphastos toco",
     "about": "The toco toucan, also known as the common toucan or giant toucan, is the largest and probably the best-known species in the toucan family. It is found in semi-open habitats throughout a large part of central and eastern South America. It is a common attraction in zoos.",
     "group": 5},

    {"commonName": "Downy Woodpecker",
     "sciName": "Picoides pubescens",
     "about": "The downy woodpecker is a species of woodpecker, the smallest in North America. Length ranges from 14 to 18 cm. Downy woodpeckers primarily live in forested areas throughout the United States and Canada, with the exception of deserts in the southwest and the northern tundra.",
     "group": 5},

    {"commonName": "Pileated Woodpecker",
     "sciName": "Dryocopus pileatus",
     "about": "The pileated woodpecker is a large, mostly black woodpecker native to North America. An insectivore, it inhabits deciduous forests in eastern North America, the Great Lakes, the boreal forests of Canada, and parts of the Pacific Coast.",
     "group": 5},

    {"commonName": "Kookaburras",
     "sciName": "Dacelo novaeguineae",
     "about": "The laughing kookaburra is a bird in the kingfisher subfamily Halcyoninae. It is a large robust kingfisher with a whitish head and a brown eye-stripe. The upperparts are mostly dark brown but there is a mottled light-blue patch on the wing coverts.",
     "group": 5},

    {"commonName": "Coraciimorphae",
     "sciName": "Coraciimorphae",
     "about": "Coraciimorphae is a clade of birds that contains the order Coliiformes and the clade Cavitaves. The name however was coined in the 1990s by Sibley and Ahlquist based on their DNA-DNA hybridization studies conducted in the late 1970s and throughout the 1980s.",
     "group": 50},

    {"commonName": "American Kestrel",
     "sciName": "Falco sparverius",
     "about": "The American kestrel, also called the sparrow hawk, is the smallest and most common falcon in North America. It has a roughly two-to-one range in size over subspecies and sex, varying in size from about the weight of a blue jay to a mourning dove.",
     "group": 6},

    {"commonName": "African Gray",
     "sciName": "Psittacus erithacus",
     "about": "The grey parrot, also known as the Congo grey parrot, Congo African grey parrot or African grey parrot, is an Old World parrot in the family Psittacidae. The Timneh parrot once was identified as a subspecies of the grey parrot, but has since been elevated to a full species.",
     "group": 6},

    {"commonName": "Black-legged Seriema",
     "sciName": "Chunga burmeisteri",
     "about": "The Black-legged Seriema is one of two living species of seriemas in the family Cariamidae.",
     "group": 6},

    {"commonName": "Peregrine Falcon",
     "sciName": "Falco peregrinus",
     "about": "The peregrine falcon, also known as the peregrine, and historically as the duck hawk in North America, is a cosmopolitan bird of prey in the family Falconidae. A large, crow-sized falcon, it has a blue-grey back, barred white underparts, and a black head.",
     "group": 6},

    {"commonName": "Prarie Falcon",
     "sciName": "Falco mexicanus",
     "about": "The prairie falcon is a medium-large sized falcon of western North America. It is about the size of a peregrine falcon or a crow, with an average length of 40 cm, wingspan of approximately 1 meter, and average weight of 720 g. As in all falcons, females are noticeably bigger than males.",
     "group": 6},

    {"commonName": "Inopinaves",
     "sciName": "Inopinaves",
     "about": "Inopinaves is a clade of neoavian birds recovered in a compressive genomic systematic study using nearly 200 species in 2015. It contains the clades Opisthocomiformes and Telluraves; the study shows that the hoatzin diverged from other birds 64 million years ago.",
     "group": 60},

    {"commonName": "Passeriformes",
     "sciName": "Passeriformes",
     "about": "A passerine is any bird of the order Passeriformes, which includes more than half of all bird species. Sometimes known as perching birds, passerines are distinguished from other orders of birds by the arrangement of their toes, which facilitates perching.",
     "group": 70},

    {"commonName": "Blue Jay",
     "sciName": "Cyanocitta cristata",
     "about": "The blue jay is a passerine bird in the family Corvidae, native to eastern North America. It lives in most of the eastern and central United States; some eastern populations may be migratory. Resident populations are also in Newfoundland, Canada; breeding populations are found across southern Canada.",
     "group": 8},

    {"commonName": "Eurasian Jay",
     "sciName": "Garrulus glandarius",
     "about": "The Eurasian jay is a species of passerine bird in the crow family Corvidae. It has pinkish brown plumage with a black stripe on each side of a whitish throat, a bright blue panel on the upper wing and a black tail.",
     "group": 8},

    {"commonName": "Florida Scrub-Jay",
     "sciName": "Aphelocoma coerulescens",
     "about": "The Florida scrub jay is one of the species of scrub jay native to North America. It is the only species of bird endemic to the U.S. state of Florida and one of only 15 species endemic to the continental United States. Because of this, it is keenly sought by birders.",
     "group": 8},

    {"commonName": "American Crow",
     "sciName": "Corvus brachyrhynchos",
     "about": "The American crow is a large passerine bird species of the family Corvidae. It is a common bird found throughout much of North America. American crows are the New World counterpart to the carrion crow of Europe and the hooded crow of Eurasia; they all occupy the same ecological niche.",
     "group": 8},

    {"commonName": "Common Raven",
     "sciName": "Corvus corax",
     "about": "The common raven is a large all-black passerine bird. It is the most widely distributed of all corvids, found across the Northern Hemisphere.",
     "group": 8},

    {"commonName": "Corvides",
     "sciName": "Corvides",
     "about": "Corvidae is a cosmopolitan family of oscine passerine birds that contains the crows, ravens, rooks, jackdaws, jays, magpies, treepies, choughs, and nutcrackers. In colloquial English, they are known as the crow family or corvids. Currently, 133 species are included in this family.",
     "group": 80},

    {"commonName": "Rose-breasted Grosbeak",
     "sciName": "Pheucticus ludovicianus",
     "about": "The rose-breasted grosbeak, colloquially called cut-throat due to its coloration, is a large, seed-eating grosbeak in the cardinal family. It is primarily a foliage gleaner. Males have black heads, wings, backs, and tails, and a bright rose colored patch on their white breast.",
     "group": 9},

    {"commonName": "House Finch",
     "sciName": "Haemorhous mexicanus",
     "about": "The house finch is a bird in the finch family Fringillidae. It is native to western North America and has been introduced to the eastern half of the continent and Hawaii. This species and the other American rosefinches are placed in the genus Haemorhous.",
     "group": 9},

    {"commonName": "Purple Finch",
     "sciName": "Haemorhous purpureus",
     "about": "Not really purple, more of an old-rose color is the male Purple Finch. This species is common in the North and East, and along the Pacific seaboard.",
     "group": 9},

    {"commonName": "Common Redpoll",
     "sciName": "Acanthis flammea",
     "about": "The common redpoll or mealy redpoll is a species of bird in the finch family. It breeds somewhat further south than the Arctic redpoll, also in habitats with thickets or shrubs.",
     "group": 9},

    {"commonName": "Emberizoidea",
     "sciName": "Emberizoidea",
     "about": "Emberizoidea is a superfamily of passerines that are referred to as the New World nine-primaried oscines that includes majority of endemics which are exclusive to the New World.",
     "group": 90}],

    "edges": [
        {"source": "Chicken", "target": "Galliformes"},
        {"source": "Chachalacas", "target": "Galliformes"},
        {"source": "Golden Pheasant", "target": "Galliformes"},
        {"source": "Mallard", "target": "Galliformes"},
        {"source": "Galliformes", "target": "Strisores"},
        {"source": "Roufus Hummingbird", "target": "Strisores"},
        {"source": "Common Nighthawk", "target": "Strisores"},
        {"source": "Chimney Swift", "target": "Strisores"},
        {"source": "Great Blue Turaco", "target": "Strisores"},
        {"source": "Strisores", "target": "Columbaves"},
        {"source": "Rock Dove", "target": "Columbaves"},
        {"source": "Bengal Florican", "target": "Columbaves"},
        {"source": "Common Cuckoo", "target": "Columbaves"},
        {"source": "Greater Roadrunner", "target": "Columbaves"},
        {"source": "Black-bellied Sandgrouse", "target": "Columbaves"},
        {"source": "Columbaves", "target": "Aequorlitornithes"},
        {"source": "Greater Flamingo", "target": "Aequorlitornithes"},
        {"source": "Pied-billed Grebe", "target": "Aequorlitornithes"},
        {"source": "Piping Plover", "target": "Aequorlitornithes"},
        {"source": "Snowy Plover", "target": "Aequorlitornithes"},
        {"source": "American Oystercatcher", "target": "Aequorlitornithes"},
        {"source": "Least Sandpiper", "target": "Aequorlitornithes"},
        {"source": "Sandwich Tern", "target": "Aequorlitornithes"},
        {"source": "Laughing Gull", "target": "Aequorlitornithes"},
        {"source": "Herring Gull", "target": "Aequorlitornithes"},
        {"source": "Arctic Tern", "target": "Aequorlitornithes"},
        {"source": "Black Skimmer", "target": "Aequorlitornithes"},
        {"source": "Aequorlitornithes", "target": "Coraciimorphae"},
        {"source": "Belted Kingfisher", "target": "Coraciimorphae"},
        {"source": "Speckled Mousebird", "target": "Coraciimorphae"},
        {"source": "Toco Toucan", "target": "Coraciimorphae"},
        {"source": "Downy Woodpecker", "target": "Coraciimorphae"},
        {"source": "Pileated Woodpecker", "target": "Coraciimorphae"},
        {"source": "Kookaburras", "target": "Coraciimorphae"},
        {"source": "Coraciimorphae", "target": "Inopinaves"},
        {"source": "American Kestrel", "target": "Inopinaves"},
        {"source": "African Gray", "target": "Inopinaves"},
        {"source": "Black-legged Seriema", "target": "Inopinaves"},
        {"source": "Peregrine Falcon", "target": "Inopinaves"},
        {"source": "Prarie Falcon", "target": "Inopinaves"},
        {"source": "Inopinaves", "target": "Corvides"},
        {"source": "Blue Jay", "target": "Corvides"},
        {"source": "Eurasian Jay", "target": "Corvides"},
        {"source": "Florida Scrub-Jay", "target": "Corvides"},
        {"source": "American Crow", "target": "Corvides"},
        {"source": "Common Raven", "target": "Corvides"},
        {"source": "Corvides", "target": "Emberizoidea"},
        {"source": "Rose-breasted Grosbeak", "target": "Emberizoidea"},
        {"source": "House Finch", "target": "Emberizoidea"},
        {"source": "Purple Finch", "target": "Emberizoidea"},
        {"source": "Common Redpoll", "target": "Emberizoidea"},
        {"source": "Corvides", "target": "Emberizoidea"}
    ]
}